language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    #- sys-img-armeabi-v7a-android-19
    #- sys-img-x86-android-16

  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - '.+'

jdk:
  - oraclejdk7

env:
  global:
    - JAVA_OPTS="-Xmx3072m"
    - GRADLE_OPTS="-Xmx2048m -XX:MaxPermSize=1024m"

script:
  - ./gradlew clean assembleDebug -stacktrace

notifications:
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

sudo: false
